export const HEADER_ADMIN=[
    {
        id:1,
        name:'Home',
        path:'/dashboard/admin'
    },
    {
        id:2,
        name:'Users',
        path:'/dashboard/admin/user'
    },
    {
        id:3,
        name:'Articles',
        path:'/dashboard/admin/article'
    },
    {
        id:4,
        name:'Courses',
        path:'/dashboard/admin/course'
    }
]